Add tests for events.go
matrix-org/gomatrix pull request #87
Opened 2021-02-26 14:07 UTC by northernSage

This PR follows #86

- [x] add tests for filters.go (100% cov)

2021-03-24 16:25 UTC, Kegsay requested changes

2021-03-24 16:25 UTC, Kegsay commented on filter_test.go
> +	if err == nil || err.Error() != "Bad event_format value. Must be one of [\"client\", \"federation\"]" {
Please don't directly compare error strings. It will suffice to just do `if err == nil` here.

2021-03-24 20:20 UTC, northernSage commented on filter_test.go
> +	if err == nil || err.Error() != "Bad event_format value. Must be one of [\"client\", \"federation\"]" {
👍🏻

2022-09-26 10:26 UTC, kegsay approved these changes
Better late than never!

2022-09-26 10:26 UTC, merged